name: Deploy to Github Pages
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploying to Github Pages
    runs-on: ubuntu-latest
    steps:
      - name: Authorizing Github action
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
        uses: oleksiyrudenko/gha-git-credentials@v1
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Clean install dependencies
        run: npm ci
      - name: Run deploy script
        run: npm run deploy
